const assert=require('node:assert/strict');
const fs=require('node:fs');
const bridge=require('../static/flashcards/js/moji_bridge.js');
const text='確かめる | たしかめる | 確認 | 出発時間を確かめる。\n～たびに | | 每當 | 名詞＋の／動詞原形＋たびに';
const rows=bridge.parse(text,'pipe');
assert.equal(rows.length,2);assert.equal(rows[1].reading,'');
assert.equal(bridge.prepare(rows,[],true).cards.length,2);
assert.equal(bridge.prepare(rows,[rows[0]],true).cards.length,1);
assert.equal(bridge.prepare([rows[0],rows[0]],[],true).cards.length,1);
assert.throws(()=>bridge.parse('missing columns','pipe'));
assert.throws(()=>bridge.parse(Array(501).fill('a|b|c|d').join('\n'),'pipe'));
assert.throws(()=>bridge.prepare([{front:'a',back:'',include:true}],[],true));
assert.equal(bridge.prepare([{front:'a',back:'',include:false}],[],true).cards.length,0);
assert.equal(bridge.parse('a\tb\tc\td','tab')[0].back,'c');
for(const u of ['javascript:alert(1)','https://www.mojidict.com.evil.test/','https://user:pass@www.mojidict.com/','https://www.mojidict.com/?token=secret'])assert.throws(()=>bridge.sourceUrl(u));
assert.equal(bridge.sourceUrl('https://www.mojidict.com/details/123'),'https://www.mojidict.com/details/123');
assert.equal(bridge.pdfLines([{str:'B',transform:[1,0,0,1,10,0]},{str:'A',transform:[1,0,0,1,0,10]}]),'A\nB');
const enricher=fs.readFileSync('static/flashcards/js/word_enricher.js','utf8');
assert.ok(!enricher.includes('api.mojidict.com'));
assert.ok(!fs.readFileSync('moji_client.py','utf8').includes('urllib'));
assert.ok(!fs.readFileSync('main.py','utf8').includes('search_moji('));
assert.ok(!fs.readFileSync('flashcard.html','utf8').includes('直接導入'));
console.log('PASS MOJi: four-column integrity, missing-data blocking, deduplication, word/grammar preservation, source URL validation, PDF line order, no internal API calls');
